export const products = [
  {
    id: 1,
    name: 'Premium Cargo Pants',
    category: 'Cargo Pants',
    article: '10086',
    sku: '10086', // SKU field added
    fabric: 'Nylon Crush Lycra Terry',
    price: 450,
    image: '/images/art-201.jpeg', // kept for backward compatibility
    images: ['/images/art-201.jpeg'], // multiple images array
    description: 'Premium cargo pants made from Nylon Crush Lycra Terry fabric, durable and comfortable.',
    inStock: true,
    colors: ['Black', 'Grey', 'Khaki', 'Olive'],
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    id: 2,
    name: 'Casual Jogger Pants',
    category: 'Casual Pants',
    article: '10075',
    sku: '10075',
    fabric: 'Bubble Crush',
    price: 420,
    image: '/images/artical-205.webp',
    images: ['/images/artical-205.webp'],
    description: 'Casual jogger pants with Bubble Crush fabric, relaxed fit for everyday wear.',
    inStock: true,
    colors: ['Grey', 'Green', 'Black', 'Brown'],
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    id: 3,
    name: 'Cotton Twill Cargo',
    category: 'Cargo Pants',
    article: '10046',
    sku: '10046',
    fabric: 'Cotton Twill',
    price: 380,
    image: '/images/art4.jpeg',
    images: ['/images/art4.jpeg'],
    description: 'Cotton twill cargo pants, classic style with sturdy fabric.',
    inStock: true,
    colors: ['Khaki', 'Camel', 'Brown', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 4,
    name: 'Nylon Cargo Joggers',
    category: 'Casual Pants',
    article: '10005',
    sku: '10005',
    fabric: 'Nylon Crush',
    price: 400,
    image: '/images/art-202.jpeg',
    images: ['/images/art-202.jpeg'],
    description: 'Nylon cargo joggers, lightweight and durable for active use.',
    inStock: true,
    colors: ['Grey', 'Khaki', 'Black', 'Brown'],
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: 5,
    name: 'Premium Nylon Pant',
    category: 'Casual Pants',
    article: '10004',
    sku: '10004',
    fabric: 'Nylon Crush',
    price: 440,
    image: '/images/art-203.jpeg',
    images: ['/images/art-203.jpeg'],
    description: 'Premium nylon pant, smooth finish and comfortable fit.',
    inStock: true,
    colors: ['Black', 'Grey', 'Brown', 'Olive', 'Camel', 'Sky'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
  },
  {
    id: 6,
    name: 'Heavy Lycra Collection',
    category: 'Heavy Lycra',
    article: '10000',
    sku: '10000',
    fabric: 'Heavy Lycra',
    price: 550,
    image: '/images/artical-6.webp',
    images: ['/images/artical-6.webp'],
    description: 'Heavy lycra collection, high elasticity and shape retention.',
    inStock: true,
    colors: ['Black', 'Grey'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
  },
];