export const products = [
  {
    id: 1,
    name: 'Premium Cargo Pants',
    category: 'Cargo Pants',
    article: '10086',
    sku: 'BXF-10086',
    fabric: 'Nylon Crush Lycra Terry',
    price: 450,
    image: '/images/art-201.jpeg',
    images: ['/images/art-201.jpeg', '/images/art-202.jpeg'],
    description:
      'Premium cargo pants crafted from Nylon Crush Lycra Terry — a durable, stretch-friendly fabric ideal for active and casual wear. Features reinforced pocket stitching, elastic waistband, and clean finishing throughout.',
    inStock: true,
    colors: ['Black', 'Grey', 'Khaki', 'Olive'],
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    id: 2,
    name: 'Casual Jogger Pants',
    category: 'Casual Pants',
    article: '10075',
    sku: 'BXF-10075',
    fabric: 'Bubble Crush',
    price: 420,
    image: '/images/artical-205.webp',
    images: ['/images/artical-205.webp', '/images/art-203.jpeg'],
    description:
      'Relaxed-fit jogger pants made from soft Bubble Crush fabric. Comfortable all-day wear with a tapered leg, ribbed cuffs, and a drawstring waistband. Perfect for retail or private-label collections.',
    inStock: true,
    colors: ['Grey', 'Green', 'Black', 'Brown'],
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    id: 3,
    name: 'Cotton Twill Cargo',
    category: 'Cargo Pants',
    article: '10046',
    sku: 'BXF-10046',
    fabric: 'Cotton Twill',
    price: 380,
    image: '/images/art4.jpeg',
    images: ['/images/art4.jpeg', '/images/art-201.jpeg'],
    description:
      'Classic cotton twill cargo with structured pockets and sturdy woven fabric. A reliable staple for wholesale buyers — easy to brand, consistent sizing, and strong demand across retail markets.',
    inStock: true,
    colors: ['Khaki', 'Camel', 'Brown', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 4,
    name: 'Nylon Cargo Joggers',
    category: 'Casual Pants',
    article: '10005',
    sku: 'BXF-10005',
    fabric: 'Nylon Crush',
    price: 400,
    image: '/images/art-202.jpeg',
    images: ['/images/art-202.jpeg', '/images/art4.jpeg'],
    description:
      'Lightweight nylon cargo joggers combining sporty utility with everyday comfort. Quick-dry Nylon Crush fabric, zip pockets, and tapered fit. Great for gym, outdoor, and streetwear lines.',
    inStock: true,
    colors: ['Grey', 'Khaki', 'Black', 'Brown'],
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: 5,
    name: 'Premium Nylon Pant',
    category: 'Casual Pants',
    article: '10004',
    sku: 'BXF-10004',
    fabric: 'Nylon Crush',
    price: 440,
    image: '/images/art-203.jpeg',
    images: ['/images/art-203.jpeg', '/images/artical-205.webp'],
    description:
      'Smooth-finish premium nylon pant with a comfortable relaxed cut. Available in the widest size range in our catalog — from M to 3XL. Ideal for inclusive sizing retail collections and teamwear orders.',
    inStock: true,
    colors: ['Black', 'Grey', 'Brown', 'Olive', 'Camel', 'Sky'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
  },
  {
    id: 6,
    name: 'Heavy Lycra Collection',
    category: 'Heavy Lycra',
    article: '10000',
    sku: 'BXF-10000',
    fabric: 'Heavy Lycra',
    price: 550,
    image: '/images/artical-6.webp',
    images: ['/images/artical-6.webp', '/images/art-202.jpeg'],
    description:
      'High-performance heavy lycra bottoms with superior elasticity and shape retention. Available in numeric waist sizing (30–44). Preferred by gyms, sports clubs, and performance apparel resellers.',
    inStock: true,
    colors: ['Black', 'Grey'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
  },
];